let shopItemsData = [
  {
    id:"asdwad",
    name:"Черный",
    price: 45,
    desc:"Lorem ipsum dolor sit amet consectetur adipisicing.",
    img:"./images/img-1.png",
  },
  {
    id:"dadfs",
    name:"Салатовый",
    price: 100,
    desc:"Lorem ipsum dolor sit amet consectetur adipisicing.",
    img:"./images/img-2.png",
  },
  {
    id:"grejoi",
    name:"Пурпурный",
    price: 25,
    desc:"Lorem ipsum dolor sit amet consectetur adipisicing.",
    img:"./images/img-3.png",
  },
  {
    id:"fgsdfgl",
    name:"Красный",
    price: 300,
    desc:"Lorem ipsum dolor sit amet consectetur adipisicing.",
    img:"./images/img-4.png",
  },
  {
    id: "thiecbawdjksadjk",
    name: "Желтый",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-5.png",
  },
  {
    id: "iuertrywebncdjksadjk",
    name: "Синий",
    price: 200,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-6.png",
  },
  {
    id: "thierytbvcbvzdhadjk",
    name: "#008080",
    price: 450,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-7.png",
  },
  {
    id: "trfoiwfcnbcawdjksadjk",
    name: "Розовый",
    price: 45,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-8.png",
  },
  {
    id: "cbvxbcvsceldk",
    name: "Оранжевый",
    price: 85,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-9.png",
  },
  {
    id: "oiopijmjkhuihb",
    name: "Оливковый",
    price: 120,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-10.png",
  },
  {
    id: "oiopijewyiohbjhib",
    name: "#37C871",
    price: 35,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-11.png",
  },
  {
    id: "rtytytuyuytyytbvncv",
    name: "Серый",
    price: 350,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-12.png",
  },
]

